### ISSUE TITLE
Just Question** Not an Issue!!

### ISSUE THREAD

**Issue by essoojay** [zuliz95/noobzvpns#1]
Please whats the right android client for this and how to setup.  Server up and running!

Thank you for this..

**Comment by zuliz95** [comment]
sorry for slow response, the program its still private beta.... waiting for app client in playstore to release then this installer stage up to stable release and public usage...

**Comment by essoojay** [comment]
Hi there,Please can I be a beta tester for you, or when is this going to be released. Thank youSojiOn 7 Feb 2023, at 7:17 am, Noobz-ID ***@***.***> wrote:﻿
sorry for slow response, the program its still private beta.... waiting for app client in playstore to release then this installer stage up to stable release and public usage...
